model:
  node_dim: 2
  edge_dim: 1
  latent_dim: 64
  n_layer: 3
train:
  seed: 1234
  data_file: data_random
  test_size: 0.1
  batch_size: 16
  shuffle_dl: True
  n_epochs: 5
  loss_fn: MSELoss
  positive_weight: False
  save_every: 64
  eval_every: 64
  device: cuda:1
opt:
  lr: 0.0005
  T_0: 32